//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infractructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DX_TESTEntities : DbContext
    {
        //public DX_TESTEntities()
        //    : base("name=DX_TESTEntities")
        //{
        //}
        public DX_TESTEntities(string connectionString)
       : base(connectionString)
        {
        }

        public virtual DbSet<ToDoItem> ToDoItems { get; set; }
    }
}
